export const PLAYER_SPEED = 400;

export const SCORE_PER_SECOND = 10;
export const ASTEROID_PASS_BONUS = 25;
export const FIERY_ASTEROID_PASS_BONUS = 100;

export const ASTEROID_BASE_SPAWN_INTERVAL = 1.45;
export const ASTEROID_MIN_SPAWN_INTERVAL = 0.8;
export const ASTEROID_INITIAL_SPAWN_TIMER = 0.85;
export const ASTEROID_SPAWN_RAMP = 0.002;

export const ASTEROID_MIN_RADIUS = 18;
export const ASTEROID_MAX_RADIUS = 42;
export const ASTEROID_BASE_MIN_SPEED = 210;
export const ASTEROID_BASE_MAX_SPEED = 285;
export const ASTEROID_SPEED_RAMP = 0.9;
export const ASTEROID_SPEED_HARD_CAP = 520;

export const ASTEROID_MIN_ROTATION_SPEED = 0.35;
export const ASTEROID_MAX_ROTATION_SPEED = 1.1;

export const FIERY_ASTEROID_CHANCE = 0.12;
export const FIERY_ASTEROID_SPEED_MULTIPLIER = 1.7;
export const FIERY_ASTEROID_ROTATION_MULTIPLIER = 1.7;
export const FIERY_ASTEROID_MIN_RADIUS_MULTIPLIER = 1.2;
export const FIERY_ASTEROID_MAX_RADIUS_MULTIPLIER = 1.3;

export const BONUS_FEEDBACK_DURATION = 0.65;
